name: Build and Upload to AWS

on:
  push:
    branches: [ master ]
#   schedule:
#     - cron: 0 0 * * 1

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install shadow-cljs
      run: npm install -g shadow-cljs

    - name: Install dependencies
      run: npm ci

    - name: Build with shadow-cljs
      run: shadow-cljs release frontend

    - name: Sync to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
        SOURCE_DIR: './public/'   # Adjust if your build output directory is different
  
    - name: Purge Cloudflare Cache
      uses: jakejarvis/cloudflare-purge-action@master
      with:
        api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        zone: db5e8df366ba3c9316392c96b6db9dfd
        purge: 'all'
